Module3 task1
htmlacademy-react/581613-six-cities-7 pull request #5
Opened 2021-06-08 20:05 UTC by IggyStooges

2021-06-09 22:08 UTC, ekazakov requested changes

2021-06-09 22:08 UTC, ekazakov commented on project/src/components/pages/room/comment-form.jsx
> +        ))}
Можешь вынести звездочки в отдельный компонент

2021-06-09 22:08 UTC, ekazakov commented on project/src/components/pages/room/room.jsx
> +          host={host}
`currentRoom` можно передать одним пропсом и сделать деструктуризацию уже в компоненте

2021-06-09 22:08 UTC, ekazakov commented on project/src/components/pages/main/place-card/place-card.jsx
> +          <img className="place-card__image" src={previewImage} width="260" height="200" alt={title} />
Вроде по ТЗ клик на картинку тоже открывает страницу оффера

2021-06-09 22:08 UTC, ekazakov commented on project/src/components/pages/main/place-card/place-card.jsx
> +          <img className="place-card__image" src={previewImage} width="260" height="200" alt={title} />
И первая картинка битая

2021-06-09 22:08 UTC, ekazakov commented on project/src/components/pages/favorites/favorites-place-card/favorites-place-card.jsx
> +        <a href="#">
Лучше сразу сделать ссылкой на страницу оффера

2021-06-10 09:18 UTC, IggyStooges commented on project/src/components/pages/main/place-card/place-card.jsx
> +          <img className="place-card__image" src={previewImage} width="260" height="200" alt={title} />
В ТЗ только про заголовок, про клик на изображение - ничего нет. Ну да фиг, с ним, пусть будет ссылка)

2021-06-10 09:40 UTC, ekazakov approved these changes

2021-06-10 09:40 UTC, ekazakov commented on project/src/components/pages/room/comment-form.jsx
> +      <RatingStars onChange={handleRatingChange} rating={rating} />
👍

2021-06-10 09:40 UTC, ekazakov commented on project/src/components/pages/main/place-card/place-card.jsx
> +        <Link to={`/offer/${id}`}>
`/offer/${id}` чтобы застраховаться от опечаток и проблем с переименованием ссылок делают отдельную ф-ю, которая возвращает роут

```
const getOfferPath(id) => `/offer/${id}`
```

2021-06-10 09:40 UTC, merged